project:
  type: website
  output-dir: ../docs
  resources:
    - archive/*.html
    - archive/*.docx
    - archive/*.rmd
  render:
    - index.qmd
    - Benchmark-workshop-information.qmd
    - SPRFMO-MSE-Workshop-Visitor-Information.qmd
    - archive/index.qmd
    - JMWG_Benchmark_ToR.qmd
    - SCW16-Paper-00.qmd
    - SCW16-Paper-01.qmd
    - SCW16-Paper-02-CPUE_Coordination.qmd
    - JMWG-2026-plan.qmd
    - "JMWG-Meeting report-01-2026.qmd"
    - "JMWG-Meeting report-02-2026.qmd"
    - SCW16-Paper-03-CPUE_MetaAnalysis.qmd
    - SC13.qmd
    - helper_scripts_guide.qmd
    - userguide/index.qmd

website:
  title: "SPRFMO Jack Mackerel Working Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: JMWG_Benchmark_ToR.qmd
        text: SCW16/ToR
      - href: SCW16-Paper-00.qmd
        text: SCW16/Paper-00
      - href: SCW16-Paper-01.qmd
        text: SCW16/Paper-01
      - href: SCW16-Paper-02-CPUE_Coordination.qmd
        text: SCW16/Paper-02
      - href: "JMWG-Meeting report-01-2026.qmd"
        text: Meeting report 01-2026
      - href: "JMWG-Meeting report-02-2026.qmd"
        text: Meeting report 02-2026
      - href: SCW16-Paper-03-CPUE_MetaAnalysis.qmd
        text: SCW16/Paper-03
      - href: SC13.qmd
        text: SC13
      - href: helper_scripts_guide.qmd
        text: Script Guide

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
