---
title: "SPRFMO SC13 Report"
subtitle: "Annex 7. Jack Mackerel Technical Annex"
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Click to show/hide code"
    theme: flatly
    css: styles.css
    embed-resources: true
  docx:
    number-sections: false
    reference-doc: custom-reference-doc.docx
    keep-md: true
    fig-width: 11
    fig-height: 9
execute: 
  echo: false
  warning: false
  message: false
  results: false
bibliography: refs.bib
csl: apa.csl  
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: false
library(jjmR)
library(tidyverse)
library(readxl)
library(here)
library(flextable)
library(equatags)
library(scales)

knitr::opts_knit$set(root.dir=here::here())
```

```{r}
#| include: false

finmodname <- "1.14"
h1nm <- geth(finmodname, "h1")
h2nm <- geth(finmodname, "h2")

h1_mod <- readJJM(h1nm, path = here::here("config"), input = here::here("input"), output = here::here("results"))
h1_diag <- diagnostics(h1_mod, plot=F)

h2_mod <- readJJM(h2nm,path = here::here("config"), input = here::here("input"), output = here::here("results"))
h2_diag <- diagnostics(h2_mod, plot=F)

bmsy_diag_h1 <- diagnostics(fixed_bmsy(h1_mod), plots = F)
bmsy_diag_h2 <- diagnostics(fixed_bmsy(h2_mod), plots = F, print = F)

h1_tidy <- tidy_JJM(h1_mod)
h2_tidy <- tidy_JJM(h2_mod)

curryr <- as.numeric(format(Sys.time(), "%Y"))

load(paste0("results/",h1nm,"_retrospective.RData"))
h1_ret<-output
h1_mohn_ssb <- round(icesAdvice::mohn(h1_ret$Stock_1$SSB$var[,1,1:6],peel=5,details=T)$rho, digits = 2)
h1_mohn_rec <- round(icesAdvice::mohn(h1_ret$Stock_1$R$var[,1,1:6],peel=5,details=T)$rho, digits = 2)

load(paste0("results/",h2nm,"_retrospective.RData"))
h2_ret<-output
h2_mohn_ssb_s1 <- round(icesAdvice::mohn(h2_ret$Stock_1$SSB$var[,1,1:6],peel=5,details=T)$rho, digits = 2)
h2_mohn_ssb_s2 <- round(icesAdvice::mohn(h2_ret$Stock_2$SSB$var[,1,1:6],peel=5,details=T)$rho, digits = 2)
h2_mohn_rec_s1 <- round(icesAdvice::mohn(h2_ret$Stock_1$R$var[,1,1:6],peel=5,details=T)$rho, digits = 2)
h2_mohn_rec_s2 <- round(icesAdvice::mohn(h2_ret$Stock_2$R$var[,1,1:6],peel=5,details=T)$rho, digits = 2)

```


{{< include annex_text.qmd >}}

# References

::: {#refs}
:::

{{< pagebreak >}}

{{< include annex_tables.qmd >}}

{{< pagebreak >}}

{{< include annex_plots.qmd >}}
