# Introduction
This document and content are based on discussions and analyses conducted at the 12th SPRFMO Scientific Committee (SC) meeting in 2024. During SC12, the model was updated with new data, and subsequently accepted by the SC. Discussions at SC12 focused on the following topics:

- Review and update of data sets; 
- Improving fits to CPUE data based on fleet dynamics; and
- Updating the weights for data from specific years in indices of abundance.

Additionally, during SC 12, a full description and user guide of the Joint Jack Mackerel Model was put forward. It can be found in [SC12-JM08](https://sprfmo.int/assets/Meetings/02-SC/12th-SC-2024/Jack-Mackerel/SC12-JM08-PER-Joint-Jack-Mackerel-Model-User-Guide.pdf), and was planned to be folded into the documentation repository.

## Scientific Name and General Distribution
The Chilean jack mackerel (*Trachurus murphyi*, Nichols 1920) is widespread throughout the South Pacific. It is found along the shelf and oceanic waters adjacent to Ecuador, Peru, and Chile, and across the South Pacific along the Subtropical Convergence Zone in what has been described as the “jack mackerel belt” that goes from the coast of Chile to New Zealand within a 35° to 50° S variable band across the South Pacific. 

## Main Management Units
At least five management units of *T. murphyi* associated to distinct fisheries are identified in the SE Pacific: the Ecuadorian fishery, which is managed as part of a more general pelagic fishery within the Ecuadorian EEZ; the Peruvian fishery, which is managed as part of a jack mackerel, mackerel and sardine fishery directed exclusively for direct human consumption taking place almost entirely within the Peruvian EEZ; the northern and the central-southern Chilean fisheries which are managed as separate management units, with the northern fishery being mostly within the Chilean EEZ and the central-southern Chilean fishery which straddles the Chilean EEZ and the adjacent high sea; and, the purely high sea fishery which is a multinational fishery being managed entirely within the context of the SPRFMO. At present there is no directed fishery for *T. murphyi* in the central and western South Pacific and around New Zealand, where incidental catches are very small. 

## Stock Structure
There are a number of competing stock structure hypotheses, and up to five and more separate stocks have been suggested: i) a Peruvian stock (northern stock) which is a straddling stock with respect to the high seas; ii) a Chilean stock (southern stock) which is also a straddling stock with respect to the high seas; iii) a central Pacific stock which exists solely in the high seas; iv) a southwest Pacific stock which exists solely in the high seas; v) and, a New Zealand-Australian stock which straddles the high seas and both the New Zealand and Australian EEZs. Regarding specifically the eastern and central South Pacific, the SPRFMO has identified the following four alternative stock structure working hypotheses: 1) jack mackerel caught off the coasts of Peru and Chile each constitute separate stocks which straddle the high seas; 2) jack mackerel caught off the coasts of Peru and Chile constitute a single shared stock which straddles the high seas; 3) jack mackerel caught off the Chilean area constitute a single straddling stock extending from the coast out to about 120°W; and, 4) jack mackerel caught off the Chilean area constitute separate straddling and high seas stocks. 

Accordingly, the Jack Mackerel Sub-group (JMSG) of the Science Working Group (SWG) of the SPRFMO at its 11th Session (SWG-11) carried out parallel assessments of the jack mackerel stock(s) in the Eastern South Pacific under the two main working hypotheses already identified. That is: jack mackerel caught off the coasts of Peru and Chile constitute a single shared stock which straddles the high seas (hypothesis 1); or that jack mackerel caught off the coasts of Peru and Chile each constitute separate stocks (the Peruvian or northern and the Chilean or southern stock) which straddle the high seas (hypothesis 2). In following up on the SWG-11 recommendations, the SPRFMO Commission at its 1st Commission Meeting requested the newly established Scientific Commission (SC) to continue the work on evaluating alternative hypotheses on jack mackerel stock population. Pending more conclusive findings on the stock population structure of jack mackerel, the 2nd Commission meeting requested the SC to continue and expand the stock assessment work under both stock hypotheses considered in the 11th SWG Meeting, and this continues to be one of the main tasks undertaken at SC12.

## Fishery
The fishery for jack mackerel in the south-eastern Pacific is conducted by fleets from the coastal states (Chile, Peru and Ecuador), and by distant water fleets from various countries, operating beyond the EEZ of the coastal states. 

The fishery by the coastal states is conducted by purse seiners. The largest fishery exists in Chile, where the fish are used for fish meal. In Peru, the fishery is variable from year to year. Here the fish are taken by purse seiners that also fish for other pelagic species (e.g., anchovy, mackerel, sardines). According to government regulations, the jack mackerel in Peru may only be used for human consumption. Ecuador constitutes the northern fringe of the distribution of jack mackerel. Here the fish only occur in certain years, when the local purse seiners may take substantial quantities (70,000 tons in 2011). Part of the catch is processed into fish meal but recently jack mackerel has been promoted to be used for human consumption. 

The distant water fleets operating for jack mackerel outside the EEZs have been from a number of parties including Belize, China, Cook Islands, Cuba, European Union (Netherlands, Germany, Poland and Lithuania), Faroe Islands, Korea, Japan, Russian Federation, Ukraine and Vanuatu. These fleets consist exclusively of pelagic trawlers that freeze the catch for human consumption. In the 1980s a large fleet from Russia and other Eastern European countries operated as far west as 130° W. After the economic reforms in the communist countries around 1990, the fishery by these countries in the eastern Pacific was halted. It was not until 2003 that foreign trawlers re-appeared in the waters outside the EEZs of the coastal states.  

The jack mackerel fishery in Chilean and offshore waters is mono-specific. In the offshore fishery, the catch consists of 90 – 98% jack mackerel, with minor bycatch of chub mackerel (*Scomber japonicus*) and Pacific bream (*Brama australis*). The available time series of jack mackerel catches in the south-eastern Pacific by Member are shown in @tbl-catch-annex, with the catch summarised by fleets in @fig-catchbyfleet and @tbl-catch-fleet.

## Management
Jack mackerel were managed by coastal states beginning in the mid-1990s. National catch quotas for jack mackerel were introduced by Peru in 1995 and by Chile in 1999. Peru introduced a ban on the use of jack mackerel for fish meal in 2002. For the international waters, the first voluntary agreement to limit the number of fishing vessels was introduced in 2010. Catch limits for jack mackerel were established for the south-eastern Pacific starting from 2011.   

## Information on the environment in relation to the fisheries 
Important environmental events such as the El Niño effect of 2016 affect oceanographic dynamics. During such events, the depth of the 15⁰C isotherm and oxycline change significantly affecting the spatial distribution of jack mackerel and their availability in different regions (see for example the work of the Habitat Monitoring Working Group of the Scientific Committee as reported in previous meetings of the Scientific Committee). The extent that such changes affect the overall population productivity is unclear. 

## Reproductive Biology
The main spawning season happens from October to December; however, spawning has been described from July to March. Gonadosomatic index and egg surveys have been used to determine the time of spawning.

# Data used in the assessment
## Data Sets
A full description of data sets used for the assessment of jack mackerel is in Annex 3 of the SC Data workshop 2015. Summaries of all data available for the assessment of the fishery in the South Pacific area are provided in @tbl-datused and @fig-metadata.

## Fishery Data
The catch data for the model represents a summation of catch values from various Members (@tbl-catch-annex) to form four “fleets”, which are intended to be consistent with the gear and general areas of fishing (@fig-catchbyfleet). The summarised catches from each of these fleets are presented in @tbl-catch-fleet.

Length data are available from all major fisheries both inside and outside the EEZs. Length distributions from Chile and the older international fleet were converted into age distributions using annual Chilean age-length keys. The more recent length composition data from China were converted to age compositions by applying EU, Russian or Chilean age-length keys as compiled by quarter of the year and then aggregated (@tbl-catchage-f1, @tbl-catchage-f2, and @tbl-catchage-f4). The EU and Russia provided age-length keys which were used to convert EU length distribution data to age. For Peruvian and Ecuadorian fisheries, length frequency data (@tbl-catchlen-f3) were used directly and fit within the model according to the specified growth curve.

In the benchmark workshop prior to SC10 (SCW14), a new Chilean ageing method was included into the assessment. This resulted in revisions to age composition data for both Chilean fleets, as well as the offshore fleet for older years. In addition, several biological variables (weight, maturity, natural mortality) were re-estimated and updated. Some detail on the revisions to the historical data and the validation approach can be found in the SCW11 report. 

In the benchmark workshop SCW14, it was further agreed that a protocol should be developed to include self-sampling data from the Offshore fleet into the assessment. As introduced in meeting documents SC10-JM03 and SC10-JM04, the protocol stipulates that length-distributions from quarters that are not sampled in the observer program but that are covered in the self-sampling, will be included into the assessment. This meant that, beginning in 2021, self-sampling data were included in the assessment data. 

Several CPUE data series are used in the model, with changes in methodology to calculate the series introduced during SC4, SC6, SC7, SC9 and SC10. Since 2022 (SC10), all CPUE series include a factor that compensates for efficiency increases of fishing operations as estimated in global effort analysis (e.g., @rousseau2019evolution). The details for each series are outlied below.

For the Chilean purse seiner fleet in the southern-central area, a “Generalized Linear Model” (GLM; @mccullagh1989generalized) approach has been used to standardise the CPUE. Here trip-based CPUE has been modelled as a linear combination of explanatory variables, with the goal of estimating a year-effect that is proportional to jack mackerel biomass. Factors in the GLM included year, quarter, zone, and vessel hold capacity. Effort units were computed as the number of days spent fishing by each vessel. This CPUE series was revised during SC4 to exclude trips with no jack mackerel catches. This was preferred because it better reflected changes in management over time (particularly the introduction of vessel-level quotas starting in 2000). To account for changes in fleet behaviour arising from the changes in management, the revised CPUE series from the GLM was modelled with a catchability change in year 2000. An overall increase of technical efficiency of 1% per year has been included for this fleet since SC10. In SC11 and SC12, alternative efficiency factors in the form of time blocks were proposed as a result of interviews with fishers (SC11-JM06, SC12-JM02). It was noted that inclusion of these proposed time blocks should be explored in a benchmark assessment.

Prior to the 2018 assessment (SC6), Peru presented a CPUE abundance index derived from the industrial purse seine fleet. This fishery has a strong focus on anchoveta and other stocks such as chub mackerel (Scomber japonicus) and bonito (Sarda chiliensis). With increasing catch rates in those fisheries, the focus on jack mackerel shifted, and the CPUE index was deemed to be no longer indicative of jack mackerel biomass. This resulted in a lack of CPUE data between 2015 and 2017. Thus, for the 2018 (SC6) assessment, CPUE indicators were calculated based on artisanal and small-scale fleets. These fleets are and have been targeting jack mackerel on a regular basis, operating at a closer distance to the coast than the industrial fleets. Historical data on catch by haul capacity for the artisanal fleets were recovered beginning in 2000. A Generalised Additive Model, in which the dependent variable (catch per trip) is gamma-distributed using a log-link function, was applied by removing the operational (holding capacity) and temporal effects (year, month). The GAM combined data from both artisanal and industrial fleets, although concerns were raised about the accuracy of the historical data (e.g., from missing fleet identifiers) and thus there is a need for continued development. In addition, an overall increase of technical efficiency of 1% per year has been included for the entire time series, beginning in SC10.

Up to the 2017 assessment (SC5), the European Union CPUE index (un-standardised), the Russian CPUE index (un-standardised) and the Chinese CPUE index (standardised with a GLM) were included as separate indices of exploitable biomass for the offshore fleet. However, it was noted that these fleets shared similar temporal and spatial dynamics and the European Union and Russian data were incorporated into a combined standardised offshore CPUE index in 2018 (SC6), with the Chinese CPUE kept separate. In 2019 (SC7), haul-by-haul data of China, EU, Korea, Vanuatu, and Russia were combined and standardised into a single Offshore CPUE time series (SC7-JM06_rev1). The standardisation procedure followed what had previously been done during SCW6. A GAM was fit to catch data with an offset of log(effort) assuming a negative binomial distribution. Vessel, month of the year, year, and El Niño effect (sea surface temperature anomaly) were taken as linear effects while two-dimensional smoothers were applied to correct for spatial effects. In SC9, the vessel explanatory variable was replaced by vessel contracting party, which resulted in CPUE indices that were similar in trend (SC9-JM02). Note that the start year of the various offshore CPUE indices has varied over time. Originally, when the European Union CPUE index was separate from the Chinese and Russian CPUE indices (SC5), the index began in 2003. In SC6, when the Russian CPUE data was incorporated into the combined Offshore index, this index was taken as beginning in 2006. From 2019 (SC7), the combined Offshore CPUE index has been included in the stock assessment as an index for the period from 2008 to the present. In addition, an overall increase of technical efficiency of 2.5% per year has been included in the time series, beginning in SC10.

In all standardised CPUE series (@tbl-indices), no explicit correction for search time has been incorporated. In some products, such as the offshore CPUE, effort in weeks is taken rather than effort by day (of positive registrations) to account for searching time. However, the inability to consistently define and accurately measure searching time remains an issue.

In SCW14, advances in fishing technological efficiency (also termed “effort creep”) were explicitly incorporated in the CPUE standardization process. As mentioned previously, annual effort creep value of 2.5% was thus applied to CPUE for the offshore fleet (details in SCW14-WD01). Evaluations of  For the other CPUE series from Chile and Peru, no formal evaluations of technological advances had been conducted. As such, an interim level of 1% efficiency improvement was applied to each series. It was agreed that further analyses would be required to understand the model reaction to the effort creep factor and noted that at this stage this factor does not appear to have an important effect on model results. SCW14 further recommended specific studies to evaluate the potential efficiency improvements for these fleets, including the technical equipment (e.g., those under consideration by the SPRFMO Scientific Committee’s Habitat Monitoring Working Group), and any other factors that could influence effective fishing effort.

The lack of a defined protocol for CPUE standardisation was noted during SCW14. Development of CPUE standardisation guidelines has thus been identified as a priority to improve the quality of the assessment.

## Fisheries Independent Data
The Chilean jack mackerel research programme has included surveys using hydro-acoustics and the daily egg production method (DEPM). Acoustic estimates have been used as relative abundance indices. For the northern region (N-Chile), data on acoustic biomass and numbers, and weights at age are available from 1984-1988, 1991, and 2006-2021. For the central-southern regions, these data are available from 1997 to 2009. The survey resumed in 2020, resulting in data points for 2020, 2022, and 2023.  Preliminary analyses during SC11 led to the recommendation of further investigation during the next benchmark assessment, prior to including these updated data in the assessment. In previous jack mackerel assessments, the acoustic survey in northern Chile was assigned the same selection-at-age curve as the northern Chile fishing fleet. However, given that the survey age composition data indicate that it catches younger ages than the fishing fleet, the SC6 considered it more appropriate to assign the survey its own selectivity. 

Egg surveys (using DEPM) were conducted on an annual basis from 1999 to 2008 along the central zone of the Chilean coast in order to assess the biomass of the spawning stock. In addition, there are estimates of abundance and numbers-at-age for the central-southern regions based on DEPM for the years 2001, 2003, 2004, 2005, 2006, 2008. Egg survey results have been used as relative abundance indices in the models. Age composition data from the acoustic and DEPM Chilean surveys are shown in @tbl-catchage-i1, @tbl-catchage-i2, and @tbl-catchage-i4. The DEPM age composition has not been updated with the new ageing criteria.

In SC10, as mentioned previously, changes were made to the Chilean ageing methods. These resulted in updated historical age composition data for both Chilean surveys and the commercial catches.

The Peruvian jack mackerel research programme includes egg and larvae surveys and hydro-acoustic stock assessment surveys. Results of these egg and larvae surveys provide information on the spatial and temporal variability of jack mackerel larvae along the Peruvian coast beginning in 1966. Acoustic biomass estimates of jack mackerel were available beginning in 1983. As these surveys had Peruvian anchoveta as the target species, the data only covered the first 80 miles, and eventually 100 miles from the coast. Corrections to compensate for this partial coverage of acoustic biomass estimates of jack mackerel were made using an environmental index describing the potential habitat of this species based on available monthly data on SST, Sea Surface Salinity (SSS), water masses (WM), oxycline depth (OD) and chlorophyll (CHL). An alternative acoustic index for Peru was presented at SC3. This was constructed using backscatter information without converting the information to biomass estimates using length-frequency data. This method was proposed to address the reduced quality of the available length-frequency data in recent years. This alternative series was included in the jack mackerel assessment in SC4, thus replacing the Peruvian acoustic series used in previous assessments. The last value provided for this series corresponds to 2013. The El Niño conditions in 2014 and 2015 affected the distribution of jack mackerel making them more dispersed and outside the area covered by the anchovy survey. Further work is needed to standardise and analyse the survey data to develop a reasonable index from the later data. The index has been retained in the current assessment and extends from 1985 to 2013.

Acoustic surveys, to estimate the biomass and distribution of jack mackerel, have also been conducted along the Chilean coast, inside and outside of the EEZ, using scientific vessels. Additionally, comprehensive acoustic surveys have been conducted from the Chilean commercial fleet, although they are not currently used in the assessment model. The time series of available acoustic estimates extends from 1984 to present day (intermittently, depending on the area). All abundance indices (fishery CPUE and survey) series used in the model are presented in @tbl-indices.

## Biological Parameters
The maturity-at-age for jack mackerel in Chile was estimated by @leal2012reproductive and has been updated by applying the new ageing criteria (SCW14-WD04) to the otoliths and histological maturity data collected between September 2011 and January 2012. Overall, the changes caused by the new aging criteria led to the understanding of a faster-growing species that is earlier to mature. Maturity-at-length was consistently observed with L~50~ at about 22-23 cm fork length (FL). The maturity-at-age values, for the single/Southern stock and those for the far north stock, are shown in @tbl-matatage.

To fit the length composition data from the far north fleet, a growth curve was used to convert age compositions predicted by the model to predicted lengths, with the conversion occurring within the model. The values for the von Bertalanffy growth parameters are given in @tbl-pars. It was noted in SC10 that the growth parameters reflected fish Total Length, whereas the data were in Fork Length. The parameters were since corrected. Ageing imprecision was previously acknowledged using an age-error matrix, as shown in @tbl-ageerror. However, because this matrix is based on expert judgement instead of empirical data, the discussions during SC4 led to selecting the final assessment model with this ageing error option turned off.

Mean weight-at-age is required for all fishing fleets and biomass indices in order to relate biomass quantities to the underlying model estimates of jack mackerel abundance (in numbers). The four weight-at-age matrices for the fishing fleets correspond to: Fleet 1 (northern Chile), Fleet 2 (south-central Chile), Fleet 3 (the far north fleet) and Fleet 4 (the offshore trawl fleet). These values are shown in @tbl-wtatage-f1, @tbl-wtatage-f2, @tbl-wtatage-f3, and @tbl-wtatage-f4.

For the Chilean fleets, the mean weight-at-age was calculated by year by taking the mean length-at-age in the catch and a length-weight relationship derived for the year. Before SC3, the same weight-at-age matrix was used for the Northern Chilean Fleet (Fleet 1) and the Southern Chilean Fleet (Fleet 2). Beginning in SC3, a weight-at-age matrix specific for Northern Chile was applied. The method used two information sources: the length-age keys and the parameters of the weight-at-length relationship from IFOP’s monitoring programme of the Chilean fisheries. The information was separated into two zones which correspond to fishing areas (and acoustic surveys) that occur in Chile. Annual weight-at-length relationship was fitted to the data by each fleet independently, and these relationships were applied to mean length-at-age within each zone, resulting in the weights-at-ages seen in @tbl-wtatage-f1 and @tbl-wtatage-f2. The information covers the period 1974-`{r} curryr`; for earlier years the weight-at-age from 1974 was used.

For the far north fleet, biological sampling data were collected by length and converted post-hoc to weights-at-age. Weight-length parameters for the von Bertalanffy weight-length curve [@vonbertalanffyQuantitativeLawsMetabolism1957] were estimated annually from these biological sampling data. The calculated weight-length parameters vere then converted to weight-at-age by applying a mean length-at-age vector, calculated using a fixed (non-annually-varying) von Bertalanffy growth curve (L~∞~ = 80.77, t~0~ = -0.356, k = 0.155, L~0~ = 15.31). These growth parameters are different from the ones used in the assessment [@tbl-pars], as they are based on Total Length, whereas the assessment uses parameters based on Fork Length. A procedure was developed (and adopted in SC11) to convert the mean length-at-age vector to a mean weight-at-age vector for the given year [@tbl-wtatage-f3]. This procedure was designed to better reflect the dynamics of the far north fishery, and to match the assessment model used for the Peruvian Area of National Jurisdiction (ANJ). Prior to SC11, the far north fleet weights-at-age for 2015-2022 were fixed at historical mean values.

The weights-at-age for the offshore fleet were derived from EU and Russian age-length keys as well as age-length keys from the south-central Chilean fleet. The EU and Russia reported both age, length, and weight data, allowing for weight-at-age to be reported for their catches based on observer programme data compiled in 2019. For China, Vanuatu and Korea, length-weight information is transformed using quarter-specific age-length keys. For most countries in this fleet, weight-at-length information is available. In some years, however, including 2018, weight-at-length data from the Chinese fleet were missing, which resulted in the use of the length-weight relationship from the south-central Chilean fleet. As of SCW14, due to the update in the Chilean ageing criteria, these weight-at-age data were updated for the time series beginning in 2015 (@tbl-wtatage-f4).

Historically, missing weight-at-age data were replaced with data from the previous year. In SCW14, it was recommended that those missing data be replaced with appropriate mean values by fleet instead. This procedure was adopted in SC11.

In SCW14, the [Natural Mortality Tool](https://connect.fisheries.noaa.gov/natural-mortality-tool/) was used to derive values of M range from roughly 0.1 to 0.35 with a mode at 0.28. The 𝐿∞ was assumed to be 80.4cm, k was assumed at 0.16 and t0 at –0.356. The value of 0.28 was used for the assessment beginning in SC10. The estimated M values are assumed to be the same for all ages and all years within the given stock (@tbl-pars).

# The Assessment Model
A statistical catch-at-age model was used to evaluate the jack mackerel stocks. The JJM (“Joint Jack Mackerel Model”) is implemented in AD Model Builder (ADMB) and considers different types of data types. The available data on the jack mackerel fishery in the South Pacific area begin from 1970 to the present year, and are described in @tbl-datused and @fig-metadata, as mentioned previously.

The JJM model is an explicitly age-structured model that uses a forward projection approach and maximum likelihood estimation to solve for model parameters. The operational population dynamics model is defined by the standard catch equation with various modifications such as those described by @fournier1982theory, @hilborn1992quantitative, and @schnute1995influence. This model was adopted as the assessment method in 2010 after several technical meetings.

During SC12, a user guide describing the population dynamics and the computational aspects of the model was presented [SC12-JM08](https://sprfmo.int/assets/Meetings/02-SC/12th-SC-2024/Jack-Mackerel/SC12-JM08-PER-Joint-Jack-Mackerel-Model-User-Guide.pdf). It includes, among other things, details on the mathematical model equations and the practical application of the model (i.e., software installation and running the model).

## JJM Developments
Since its adoption, the JJM model has been improved by participating scientists. The most notable changes have been options to include length composition data (and specifying or estimating growth) and the capability to estimate natural mortality by age and time (although this capability is not used). The model is flexible and permits the use of catch information either at age or size for any fleet, and explicitly incorporates regime shifts in population productivity.

The model consists of several components, (i) the dynamics of the stock; (ii) the fishery dynamics; (ii) observation models for the data; and (v) the procedure used for parameter estimation (including uncertainties).

A JM modelling workshop was held from 7/8 – 9/10 June 2022, attended by 33 people, with the aim of building capacity for utilization of the existing JJM model but also identifying several ways in which it could be improved to enhance transparency and ease of use. These ideas were subsequently fed into the JM Benchmark Workshop in July (SCW14). 

### Stock dynamics
Recruitment is assumed to occur in January while the spawning season is assumed to be an instantaneous process occurring in mid-November. The population’s age composition considers individuals from 1 to 12+ years old. In all cases a stochastic Beverton-Holt relationship (@beverton1957dynamics) between stock and recruitment is included. Each cohort survives an age-specific mortality composed of fishing mortalities at-age by fleet and natural mortality (assumed to be constant over time and age). The model is not spatially-explicit, although the fisheries operate in geographically distinct areas. The initial population is based on an equilibrium condition and occurs in 1958 (12 years prior to the model start in 1970).

### Fishery dynamics
The interaction of the fisheries with the population occurs through fishing mortality. Fishing mortality is assumed to be a composite of several processes – selectivity (by fleet), which describes the age-specific pattern of fishing mortality; catchability, which scales fishing effort to fishing mortality; and effort deviations, which are a random effect in the fishing effort − fishing mortality relationship. The selectivity pattern is non-parametric and assumed to be fishery-specific and time-variant. Catchability is specific to each of the seven abundance indices. The model includes temporal variation in both fishery and index selectivity patterns at the annual and regime scales, depending on the index and the stock structure hypothesis. More detail is included in the subsequent section.

### Observation models for the data
There are four data components that contribute to the log-likelihood function: the total catch data, the age-frequency data, the length-frequency data and the abundance indices. 

The probability distributions for the age and length-frequency proportions are assumed to be approximated by multinomial distributions. Sample size is specified to be gear-specific but mostly constant over years. For the total catch by fishery (4) and the abundance indices (7), a log-normal assumption has been assumed with constant CV; the CV for the fisheries being 0.05 whereas the CV for the abundance indices depends on the index. Beginning in 2018, as discussed in SC4 and agreed upon in SCW6, the Francis T1.8 weighting method (@francis2011data) is used to assign weighted sample sizes for age-frequency data. The data weights were updated during the JM 2022 benchmark (SCW14).

### Parameter estimation
The model parameters are estimated by maximising the log-likelihoods of the data plus the log of the probability density functions of the priors and smoothing penalties specified in the model. Estimation was conducted in a series of phases, the first of which used arbitrary starting values for most parameters. The model has been implemented and compiled in ADMB and its characteristics can be consulted in @fournier2012ad.

## Stock Structure Hypotheses
As mentioned in the introduction, during SWG11, two types of population structure were evaluated, and this was continued for subsequent evaluations. Beginning in 2020 (SC8), models under the single-stock hypothesis carry “h1” in front of the model number, models under the two-stock hypotheses carry “h2” in front of the model number. Some of the differences in the two models, mainly in the treatment of the data, selectivity, and recruitment, are described later in the Annex.

## Model Details
Parameters estimated conditionally are listed in @tbl-symbols. The most numerous of these involve estimates of annual and age-specific components of fishing mortality for each year and for each of the four fisheries identified in the model. Parameters describing population numbers at age 1 in each year (and years prior to 1970 to estimate the initial population numbers at ages 1-12+) were the second most numerous type of parameter.  

Equations and specifications for the assessment model are given in @tbl-eqs and @tbl-objfun. @tbl-cv contains the initial variance assumptions for the indices and the age and length compositions.

The treatment of selectivity patterns and how they are shared among fisheries and indices are given in @tbl-sel-h1 for the single-stock hypothesis (hypothesis 1), and @tbl-sel-h2-s1 and @tbl-sel-h2-s2 for the two stocks under the two-stock model configurations (hypothesis 2). Selectivity for the Far North fleet was specified with a regime shift in 2002 under the two-stock hypothesis, while annual variations beginning in 1981 were specified for the same fleet under the single-stock hypothesis. A growth function within the model was specified to convert model-predicted age compositions to length compositions, in order to fit the model to the length composition data (@tbl-pars).

Equilibrium-based reference points are calculated within the jjm model. The model estimates values of Maximum Sustainable Yield (MSY) and the fishing mortality rate that produces MSY (F~MSY~) using a Newton-Raphson minimization routine that finds the value of fishing mortality, given the terminal year relative catches (and selectivities-at-age) by fleet, and the terminal year weights-at-ages for each fleet, that maximizes catch. Since weights-at-age and “effective” selectivity change each year, these values can vary. MSY is thus defined as the maximum amount of catch that allows the remaining stock to generate sufficient recruitment to maintain the population at the same level. B~MSY~ is taken as the long-term average of biomass fished under MSY. Between 2013 and 2021, a provisional B~MSY~ level of 5.5 million tons was instated based on analyses executed at SC03. In SCW14, the provisional management reference point for B~MSY~ was revised to a ten-year average of the model-estimated B~MSY~. A limit reference point B~lim~ (where B refers to spawning biomass) for the single-stock hypothesis was also developed during SCW14. B~lim~ was defined as the spawning biomass level below which recruitment would likely be impaired. As such, there should be no fishing when the current spawning biomass is estimated to be below Blim. For jack mackerel, B~lim~ was computed from the lowest ratio of historical spawning biomass relative to the most-recently-estimated unfished spawning biomass. In SCW14, this ratio was estimated to be 8% of the unfished spawning biomass.


## Description of Model Explorations
As SC12 was an update assessment, the main model explorations involved incrementally adding new data components relative to the model and data adopted from SC11. These are labelled “h1_0.x” and “h2_0.x", where `h1` and `h2` represent the stock structure hypothesis and `x` represents the number when a component was added (@tbl-modruns). 

The rationale for the main updates and data revisions occurring through model configurations 0.00 to 0.10 has been explained in the “Data used in the assessment” section, earlier in this Annex. 

Thereafter, Model 0.10 was renamed as Model 1.00. with an updated control file to reflect changes in selectivity for the current year, as was done in previous years.

The dynamics of the offshore fleet changed significantly in 2021, with the fishery fishing further north than they had in the past. Previous assessments had accepted base models with added flexibility in selectivity for 2022 (SC10-1.02) and a downweighted offshore CPUE value in 2022 (SC11-1.07). During SC12, in Model 1.01, the flexibility in the offshore fishery selectivity pattern was moved to 2021, with a break in estimation of catchability for the associated CPUE index in the same year. The CV for the CPUE time series was thus updated to be the same across all years, similar to the other CPUE indices.

A preliminary sensitivity analysis was conducted to test the replacement of the Chilean CPUE index with one standardised using a spatio-temporal Bayesian model ([SC12-JM06](https://sprfmo.int/assets/Meetings/02-SC/12th-SC-2024/Jack-Mackerel/SC12-JM06-CHL-Update-on-CPUE-standardization-for-the-Chilean-JM-fishery-in-central-southern-Chile-using-spatio-temporal-Bayesian-models.pdf); Models 1.02 and 1.03). These sensitivity analyses only involved the replacement of the data, and as such remain preliminary and requires further investigation.

During SC12, several errors in the model updating process and the data submissions were identified, resulting in Models 1.04 and 1.05. There was a difference in treatment of selectivity between the Northern Chile fleet and the other three fleets - selectivity was not allowed to vary in the final year of the model. This was likely due to an oversight during SC6, and was corrected in Model 1.04. Some anomalies were also noted in the age composition data for the Chilean Acoustic North survey and the Northern Chile fishery, where age-0 fish were recorded in the first two quarters of the year. This resulted in some corrections to the present year data, and were incorporated into the data-bridging exercise. More errors were found in data from earlier years, which were then corrected in Model 1.05.

Subsequently, it was noted that the Chilean Acoustic North survey had consistently provided data to the SC in recent years. As such, there was increased confidence in the recent trends from those data, which were reflected in Model 1.06. The CV for those data points were reduced to be the same across the entire time series.

Finally, during SC12, it was noted that updating the CPUE values from the previous year had a significant impact on the perception of the stock. This was likely due to the fact that the CPUE values for the current year only reflected the dynamics for the first half of the assessment year. Consequently, they may not be reflective of the abundance trends of that year. As such, Model 1.07 down-weighted the CPUE value of the current year.

The final model used the Francis weights agreed upon by SCW14 for the multinomial age composition sample sizes, and these weights were not updated in this assessment update. Also, the model took a precautionary approach to assessment and advice. It assumed low steepness (h=0.65) and used the most recent recruitment time-series (2001-2015), similar to assessments prior to SC5. Recruitment used in the forecast was taken directly from the assessment. 

Beginning in SC9, efforts have been made to increase the reproducibility and transparency of the assessment process. A centralised repository for data submissions was created on Teams to facilitate ease of access. R scripts were developed to document the assessment update process. These scripts included code to 1) read in, analyse, and raise catch at age/length data, 2) incrementally update data files for the bridging exercise from the previous year’s assessment to the new assessment, 3) update model files for model sensitivity runs, 4) conduct projections with the final model, and 5) create an HTML document for result presentation. Scripts for processing the data (1) are found in the [jjmData](https://github.com/SPRFMO/jjmdata) repository, whereas the assessment scripts can be found on the [jjm](https://github.com/SPRFMO/jjm) repository, in the assessment folder.

# Results
Results from incrementally updating the data and the model (Models 0.00 to 1.00) indicated a generally increasing trend in biomass for recent years. For the single-stock hypothesis, updating the Peruvian CPUE series (Model h1_0.09) had the largest impact on the recruitment estimates in recent years, resulting in an increase in biomass estimates. This impact was not seen in the two-stock hypothesis, however. Updating the 2023 fishery age composition data (Model h2_0.02) and the Chilean CPUE time series (Model h2_0.08) resulted in a decrease in the rate of increase for the biomass of the south stock in recent years. The biomass of the north stock showed a slight decrease in recent years, and historical estimates decreased in magnitude, in part from updating the Peruvian CPUE time series (Model h2_0.09).

Incorporating a regime shift in selectivity for the offshore fleet had negligible impacts on the perception of the stock (Model 1.01). A naive replacement of the Chilean CPUE with one standardised with a spatio-temporal Bayesian model resulted in lower biomass estimates for recent years, for the single-stock hypothesis and for the south stock of the two-stock hypothesis (Models 1.02 and 1.03). This analysis is preliminary, and as such more research would be necessary before incorporating this time series in the assessment. Corrections to the treatment of selectivity and the anomalous data had negligible impact on stock perception (Models 1.04 and 1.05). Increasing the confidence in the acoustic north survey data resulted in higher biomass and recruitment estimates for the single-stock hypothesis and the south stock of the two-stock hypothesis (Model 1.06). Conversely, reducing the confidence in the current year's CPUE values resulted in lower biomass estimates for recent years (Model 1.07).

It was decided that the final model for SC12 was to be Model 1.07, which included 1) a change in selectivity pattern in 2021 for the Offshore fleet, 2) a change in selectivity in 2024 for the Northern Chile fleet, 3) increased confidence in the Acoustic North survey, and 4) a down-weighting of all CPUE values for the current year. Overall, the stock (or stocks; depending on the stock structure hypothesis used) shows continued increasing trends in biomass, similar to previous years. 

An analytical retrospective analysis involves running the model multiple times, each time removing the final year of data (for five years). The retrospective analysis shows that Model `{r} h1nm` tended to slightly under-estimate SSB, with a Mohn’s rho of `{r} h1_mohn_ssb` (@fig-retro-ssb-h1). Recruitment tended to also be under-estimated, with a Mohn’s rho of `{r} h1_mohn_rec` (@fig-retro-r-h1). The negative bias in recruitment is likely due to the fact that recruitment in recent years has been very high, and estimated recruitment in the final year reverts to a longer-term mean. Model `{r} h2nm` showed little retrospective pattern in SSB for the south stock (Mohn’s rho of `{r} h2_mohn_ssb_s1`), but had a tendency to over-estimate SSB for the north stock (Mohn’s rho  of `{r} h2_mohn_ssb_s2`; @fig-retro-ssb-h2). The model also tended to under-estimate recruitment for the south (Mohn’s rho of `{r} h2_mohn_rec_s1`), with an inverse but somewhat worse pattern for the north stock (Mohn’s rho of `{r} h2_mohn_rec_s2`; @fig-retro-r-h2).

An alternative to the analytical retrospective analysis, which is based on the current model formulation, the “historical retrospective analysis” instead compares quantities derived from assessments previously adopted by the SC. This indicates the year-to-year changes in estimates of stock trends and reference points. This analysis was only conducted on Model `{r} h1nm` (raw values for biomass found in @tbl-histssb; graphically visualised in @fig-histretroquants and @fig-histretrorefpts). The results were mostly in line with the previous year’s estimates, albeit with the SC12 model showing a larger increase in biomass beginning in 2020, relative to the previous models. The trends in the CPUE and age composition data were likely driving this change. Estimates of fishing mortality in recent years remain similar to that of the previous SCs, almost following the estimates from SC10 and SC11 exactly. Recruitment estimates appear mostly in line with those of previous models, similar to SC10 and SC11. Overall, the trends appear consistent over time (@fig-histretroquants). Another interesting comparison to make is that of the management reference points (biomass (B) at maximum sustainable yield (MSY) and fishing mortality (F) at MSY; B~MSY~ and F~MSY~ respectively) estimated within the model over the years. Previously, updates to the ageing methodology in 2022 likely led to a change in the perception of stock biomass, likely resulting in an increase in the estimate of B~MSY~. The updates to the data for 2024 resulted an increase in the model estimate of B~MSY~ and a decrease in F~MSY~ relative to the SC11 model (@fig-histretrorefpts). The stock has consistently been estimated as rebuilt since 2018, and not subject to overfishing since 2013, relative to the dynamically-estimated MSY reference points.

Fishery mean weights-at-age assumed for all models are shown in @fig-wtatagefsh, and those for the surveys are shown in @fig-wtatagesrv. Estimates of numbers-at-age from Model `{r} h1nm` are given in @tbl-natage-h1, and Model `{r} h2nm` results are in @tbl-natage-h2-s1 (southern stock) and @tbl-natage-h2-s2 (northern stock). Both models show similarly good fits to the fishery composition data (@fig-agefitsfshh1-1, @fig-agefitsfshh2-1, @fig-agefitsfshh1-2, @fig-agefitsfshh2-2, @fig-lenfitsfshh1, @fig-lenfitsfshh2, @fig-agefitsfshh1-4, and @fig-agefitsfshh2-4), although both models predicted more older fish than were found in 2024, for the south-central Chile and the offshore trawl fleets (@fig-agefitsfshh1-2,@fig-agefitsfshh2-2, @fig-agefitsfshh1-4 and @fig-agefitsfshh2-4). Both models also fit the length compositions from the far north fleet well, although the data showed more fish in the plus group for 2024 than the model predicted (@fig-lenfitsfshh1 and @fig-lenfitsfshh2). The fits to age composition data from the surveys are given in @fig-agefits-srv-h1-1, @fig-agefits-srv-h2-1, @fig-agefits-srv-h1-2, @fig-agefits-srv-h2-2, @fig-agefits-srv-h1-3, and @fig-agefits-srv-h2-3. Both models appear to fit those data relatively well. Models `{r} h1nm` and `{r} h2nm` fit the indices similarly well (@fig-indfitsh1 (h1), @fig-indfitsh2-1 (h2 south), and @fig-indfitsh2-2 (h2 north)); relative abundance estimates remained within the uncertainty bounds of the data. Both models show an increasing estimate of mean fishery age over the last decade across the three fleets for which age composition data were available (@fig-meanagefshh1 and @fig-meanagefshh2). This increase is less pronounced in the survey (@fig-meanagesrvh1 and @fig-meanagesrvh2), where only the Chile acoustic north survey has age composition data after 2010. The single-stock model predicted the increasing mean length for the far north fleet relatively well (@fig-meanlenfshh1). The two-stock model, on the other hand, consistently under-estimated the mean length for that fishery after 2020 (@fig-meanlenfshh2). Selectivity estimates for the fishery and indices are shown over time in @fig-selfshh1, @fig-selfshh2, @fig-selsrvh1, and @fig-selsrvh2.

For SC12, B~MSY~ was estimated to be approximately `{r} round(mean(rev(h1_mod[[1]]$output[[1]]$msy_mt[,10])[1:10]) / 1e3, 2)` million t under the single-stock hypothesis (`{r} h1nm`), and `{r} round(mean(rev(h2_mod[[1]]$output[[1]]$msy_mt[,10])[1:10]) / 1e3, 2)` and `{r} round(mean(rev(h2_mod[[1]]$output[[2]]$msy_mt[,10])[1:10]) / 1e3, 2)` million t for the south and far north stocks respectively under the two-stock hypothesis (`{r} h2nm`). 

```{r}
# To get fished over unfished total biomass
h1_uf_b <- rev(h1_mod[[1]]$output[[1]]$TotBiom_NoFish[,2])[1]
h1_f_b <- rev(h1_mod[[1]]$output[[1]]$TotBiom[,2])[1]
h1_brat <- round((h1_f_b / h1_uf_b) * 100)

h2_1_uf_b <- rev(h2_mod[[1]]$output[[1]]$TotBiom_NoFish[,2])[1]
h2_1_f_b <-  rev(h2_mod[[1]]$output[[1]]$TotBiom[,2])[1]
h2_brat_1 <- round((h2_1_f_b / h2_1_uf_b) * 100)

h2_2_uf_b <- rev(h2_mod[[1]]$output[[2]]$TotBiom_NoFish[,2])[1]
h2_2_f_b <-  rev(h2_mod[[1]]$output[[2]]$TotBiom[,2])[1]
h2_brat_2 <- round((h2_2_f_b / h2_2_uf_b) * 100)
```

A summary of the time series stock status (spawning biomass, F, recruitment, total biomass) for the single-stock hypothesis (`{r} h1nm`) is shown in @fig-sumsheet-h1. It is noted that the biomass has been steadily increasing over the last decade, and is now above the B~MSY~ management reference point. Currently, the biomass is estimated to be around `{r} h1_brat`% of what is estimated to have occurred had there been no fishing (@fig-unfshbio-h1).

Under the two-stock hypothesis (`{r} h2nm`), conditions of the jack mackerel stock in its entire distribution range in the southeast Pacific show a continued recovery since the time-series low in 2010. It is noted that under the two-stock model, the southern stock shows an increasing trend in biomass over the last decade (@fig-sumsheet-h2-1), while the northern stock only shows an increase in biomass beginning in the middle of the last decade (@fig-sumsheet-h2-2). The southern stock showed similar results to that of the single-stock hypothesis, although SSB was estimated slightly higher under the former scenario. Estimates of exploitation rate for the northern stock were comparable to recent years, remaining at relatively low levels. @fig-unfshbio-h2-1 and @fig-unfshbio-h2-2 show the current total biomass to be approximately `{r} h2_brat_1`% and `{r} h2_brat_2`% of unfished total biomass for the southern and the far north stocks respectively.

Estimated annual fishing mortality rates (combined fleets) were high starting in about 1992 across the entire jack mackerel population, but have declined in the past years, regardless of stock structure hypothesis or designation @fig-sumsheet-h1, @fig-sumsheet-h2-1, and @fig-sumsheet-h2-2). Similarly, fishing mortality rates at age showed a decline in fishing pressure, after the mid-1990s, with the biggest changes occurring in older fish (@tbl-fatage-h1, @tbl-fatage-h2-s1, and @tbl-fatage-h2-s2). Time series of quantities derived by Model `{r} h1nm` are presented in @tbl-sum-h1, whereas those of Model `{r} h2nm` are in @tbl-sum-h2-s1 (southern stock) and @tbl-sum-h2-s2 (far north stock).

Short, medium and long-term predictions for the stock(s) under different fishing mortalities are found under @tbl-risk-h1 (`{r} h1nm`) and @tbl-risk-h2 (`{r} h2nm`). In all scenarios, selectivity-at-age patterns were fixed at the final year values for each fleet. During SC11 and SC12, the risk tables were expanded to include additional fishing scenarios, by projecting using a fishing mortality rate that was calculated to provide the present year's Total Allowable Catch (TAC) in the next year. For example, the scenario F~TAC2024~ would produce a catch of 1,242 kt (which is the 2024 catch limit) in 2025, based on selectivity patterns from 2024. Subsequent years in the projection would be subject to the same fishing mortality rate and selectivity patterns. Other scenarios included multipliers on that fishing mortality rate. It should be noted that comparisons to B~MSY~ are based on an average of B~MSY~ over the past 10 years, as specified at SWG14, which gives a larger B~MSY~ value than recent annually-estimated values of B~MSY~. Additionally, recruitment has increased in recent years to about the long-term average mean, based on a recruitment curve estimated from 2000 to `{r} curryr-3` for the southern/single stock. However, the recruitment curve estimated from the period of low recruitment (2001 - 2015) was used for projections. It should also be noted that selectivity patterns across all fleets in recent years have shifted to favour older fish, which would also have impacted the estimated reference points. The validity of these assumptions and their impacts on resultant reference points and management advice remain a topic for further investigation.

# Management Advice
New data and indicators on the status of the jack mackerel stock suggest that conditions evaluated in detail from the last update assessment are relatively unchanged. The population trend is estimated to be increasing. The indications of stock improvement (higher abundance observed in the acoustic survey in the northern part of Chile, better catch rates apparent in all fisheries for which data are available, and increase in average age in the Chilean fisheries) drive the increase.

Historical fishing mortality rates and patterns relative to the provisional biomass target are shown in @fig-sumsheet-h1 for Model `{r} h1nm`. Near-term spawning biomass is expected to increase from `{r} (rev(h1_mod[[1]]$output[[1]]$SSB[,2])[2] / 1000) %>% signif(3)` million t in `{r} curryr` to `{r} (rev(h1_mod[[1]]$output[[1]]$SSB[,2])[1] / 1000) %>% signif(3)` million t in `{r} curryr + 1` (with approximate 90% confidence bounds of `{r} (rev(h1_mod[[1]]$output[[1]]$SSB[,4])[1] / 1000) %>% signif(3)` – `{r} (rev(h1_mod[[1]]$output[[1]]$SSB[,5])[1] / 1000) %>% signif(3)` t). Under the two-stock hypothesis, historical fishing mortality rates and patterns relative to the biomass targets estimated by Model `{r} h2nm` are shown in @fig-sumsheet-h2-1 and @fig-sumsheet-h2-2. Near-term spawning biomass is expected to increase from the `{r} curryr` estimate of `{r} (rev(h2_mod[[1]]$output[[1]]$SSB[,2])[2] / 1000) %>% signif(3)` million t to `{r} (rev(h2_mod[[1]]$output[[1]]$SSB[,2])[1] / 1000) %>% signif(3)` million t in `{r} curryr + 1` for the southern stock (with approximate 90% confidence bounds of `{r} (rev(h2_mod[[1]]$output[[1]]$SSB[,4])[1] / 1000) %>% signif(3)` – `{r} (rev(h2_mod[[1]]$output[[1]]$SSB[,5])[1] / 1000) %>% signif(3)` million t), and decrease from `{r} (rev(h2_mod[[1]]$output[[2]]$SSB[,2])[2] / 1000) %>% signif(3)` million t to `{r} (rev(h2_mod[[1]]$output[[2]]$SSB[,2])[1] / 1000) %>% signif(3)` million t for the far north stock (with approximate 90% confidence bounds of `{r} (rev(h2_mod[[1]]$output[[2]]$SSB[,4])[1] / 1000) %>% signif(3)` – `{r} (rev(h2_mod[[1]]$output[[2]]$SSB[,5])[1] / 1000) %>% signif(3)` million t).

Recent increases in the model-calculated B~MSY~ values (which is different from the constant B~MSY~) would imply an estimate of SSB that is approximately twice of B~MSY~ for both the single-stock and the two-stock hypotheses. These increases are are likely due to changes in selectivity of all fisheries combined.

As was the case last year, the stock is estimated to be in the third tier of the harvest control rule (as defined in the SCW14 report, para 62.d). Within the third tier of the harvest control rule, catches should be limited to a fishing mortality rate based on F~MSY~, which would be expected to result in catches in 2025 of 4,997 kt. This expected catch is more than four times the current catch levels, and likely due to inflated F~MSY~ estimates from strong selection on older fish. However, in line with the adopted harvest control rule ([SCW14](https://sprfmo.int/assets/Meetings/SC_WS/SCW14-Jack-Mackerel-2022/SPRFMO-SC-JM-Benchmark-Workshop-2022-Report-SCW14.pdf); para 62.d), catch advice (and TACs) cannot exceed a 15% increase from the advice in the previous year. Therefore, the SC12 recommended the 2025 TAC to be **at or below 1,428 kt**. This represents a 15% increase from the 2024 TAC, and applies throughout the range of jack mackerel. Notably, this level of catch was estimated to be at about equal to the fishing effort estimated for 2024. This advice is also independent from alternative stock structure hypotheses.

Projections show a high likelihood of the biomass being above B~MSY~ in `{r} curryr+1`, even under the most conservative recruitment productivity scenario evaluated (`{r} h1nm`.ls and `{r} h2nm`.ls; @tbl-risk-h1 and @tbl-risk-h2). A re-evaluation of the rebuilding plan is recommended to analyse sustainable exploitation rates of the rebuilt jack mackerel stock. 

# Assessment Issues
Based on results from the 2022 benchmark workshop, assessment plans for the next benchmark should be developed several months prior. Doing so will allow data coordinators to configure alternatives and conduct a careful evaluation of all available information to best guide the Commission. One of the higher priority items for consideration continues to be the catch-at-age estimates (based on age-determinations being conducted from different labs) and mean body weights at age assumed in the model. Another priority for consideration is the development of guidelines for standardisation of CPUE indices and the collection of relevant data. In particular, evaluations of efficiency improvements for the Peruvian and Chilean fishing fleets were noted. Results of the data weighting and the retrospective pattern analysis also warrant further investigation.

The issue of evaluating sensitivities to the early fishery age composition data was raised. The SC noted that this might be a fruitful avenue for investigation in subsequent assessments, particularly since these data (pre-1990) are less well-documented. Residual patterns in the age composition for the North Chilean fleet remain unresolved, and warrant further investigation as well.

The validity of the assumptions used in model projections and the sensitivity of the results to those assumptions, both to estimate reference points and to conduct the risk analyses, require further research. In particular, the assumptions on selectivity patterns and recruitment regimes are likely to have a large impact on the management outcomes.

The need for a closer evaluation comparing the performance of the model under the single-stock and two-stock hypotheses was noted, likely conducted using simulation and MSE.
