---
title: "Smoothing body mass-at-age"
format: pdf
---

 Mean weights
for each age $i$,  $i$= (1, 2,…,12) are estimated given actual observed mean and 
variances in
weight-at-age over the period 1970-2022. The values of based on available data
and (if this option is selected) estimates the parameters subject to the
natural constraint:
    $$w_{ta}^{future} \sim \mathcal{N}(\bar{w_{a}},\,\sigma_{w_a}^{2})$$ 
Note that this converges to the mean values over the time series of data (no
other likelihood component within the model is affected by future mean
weights-at-age).

Subsequently, this method was refined to account for current-year survey data and both 
cohort and year effects.  The model for this is:
\begin{align}
\hat{w}_{ta} &= \bar w_a e^{\upsilon_t} & a=1, \, t \ge 1970 \\
\hat{w}_{ta} &= \hat{w}_{t-1,a-1} + \Delta_a e^{\psi_t} & a > 1, \, t > 1970 \\
\Delta_a     &= \bar w_{a+1} - \bar w_a & a<A  \\
\bar w_a     &= \alpha \left\{L_1+ \left(L_2-L_1\right)\left(\frac{1-K^{a-1}}{1-K^{A-1}}\right)\right\}^3  \\
\end{align}
where the fixed effects parameters are $L_1, L_2, K,$ and $\alpha$ while the random effects parameters 
are $\upsilon_t$ and $\psi_t$. 

Since observation errors are unavailable for the estimates provided, 
we assumed a fixed vector by age:


| Age | 1   | 2   | 3  | 4  | 5  | 6  | 7   | 8   | 9   | 10  | 11  | 12  |
| --- | --- | --- | -- | -- | -- | -- | --- | --- | --- | --- | --- | --- |
| CV  | 10% | 10% | 5% | 5% | 5% | 8% | 10% | 10% | 13% | 15% | 18% | 20% |
